# Generated by Django 3.2 on 2021-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='created_time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
