# Generated by Django 3.2 on 2021-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20210423_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-created_time'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='publications',
            name='slug',
            field=models.SlugField(default='0'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
