# Generated by Django 3.2 on 2021-04-25 08:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20210425_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
