# Generated by Django 3.2 on 2021-04-25 08:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_publications_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
